### ISSUE TITLE
sql-tag whitespace issues

### ISSUE THREAD

**Issue by icodeforlove** [seegno/sequelize-sql-tag#5]
this module is broken currently with whitespaces

https://github.com/seegno/sql-tag/issues/6

for anyone that is using sequelize you can just do this

``` javascript
const SQL = (query, ...bind) => ({
    bind,
    query: query.reduce((result, part, index) => `${result}$${index}${part}`)
});
```

**Comment by ruimarinho** [comment]
Please take a look at my reply on https://github.com/seegno/sql-tag/issues/6#issuecomment-249416761.
