### ISSUE TITLE
Support sequelize 4.x.x

### ISSUE THREAD

**Issue by rplopes** [seegno/sequelize-sql-tag#6]
Upgrading sequelize to the new 4.0.0 version is failing on projects with `sequelize-sql-tag` because it doesn't support that version yet. Here's the returned error:

```
npm WARN sequelize-sql-tag@2.0.0 requires a peer of sequelize@>=3.14.0 but none was installed.
npm ERR! code 1
```

**Comment by ruimarinho** [comment]
Please refer to https://github.com/seegno/sequelize-sql-tag/pull/7#issuecomment-249415737 for context.
